import Head from 'next/head';
import HomeFooter from '../Components/HomePageLayout/HomeFooter';
import HomeHeader from '../Components/HomePageLayout/HomeHeader';
import PresentationPhoto from '../img/charles_cantin_photo.jpg';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHeader/>
        <main className={styles.main}>
          <Image
            src={PresentationPhoto}
            alt= 'photographie de Charles Cantin le photographe'
            layout='fill'
            objectFit='cover'
          />
        </main>
      <HomeFooter/>
    </div>
  )
};

export default Home;
